languageCode = "en"
languageName = "English"
weight = 1
title = "Blowfish"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/blowfish_logo_transparent.png"
  description = "A powerful, lightweight theme for Hugo."

[params.author]
  name = "Archisa Bhattacharya"
  email = "archisa28@gmail.com"
  image = "img/blowfish_logo.png"
  headline = "A powerful, lightweight theme for Hugo."
  bio = "A powerful, lightweight theme for Hugo."
  links = [
    { x-twitter = "https://twitter.com/archisa2" },
    { github = "https://github.com/archipelagoing" },
  ]